name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Build Project and Create Zip
        run: |
          dotnet publish 'Flow.Launcher.Plugin.AppsSnapshoter.csproj' -r win-x64 -c Release -o "AppsSnapshoter-${{steps.version.outputs.prop}}"
          .\Fetch-HandleExecutable.ps1 -OutputPath "AppsSnapshoter-${{steps.version.outputs.prop}}"
          7z a -tzip "AppsSnapshoter-${{steps.version.outputs.prop}}.zip" "./AppsSnapshoter-${{steps.version.outputs.prop}}/*"
          rm -r "AppsSnapshoter-${{steps.version.outputs.prop}}"
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "AppsSnapshoter-${{steps.version.outputs.prop}}.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}